/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManualReviewRouteImport } from './routes/manual-review'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxConfigurationRouteImport } from './routes/inbox-configuration'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const ManualReviewRoute = ManualReviewRouteImport.update({
  id: '/manual-review',
  path: '/manual-review',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxConfigurationRoute = InboxConfigurationRouteImport.update({
  id: '/inbox-configuration',
  path: '/inbox-configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inbox-configuration': typeof InboxConfigurationRoute
  '/login': typeof LoginRoute
  '/manual-review': typeof ManualReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inbox-configuration': typeof InboxConfigurationRoute
  '/login': typeof LoginRoute
  '/manual-review': typeof ManualReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inbox-configuration': typeof InboxConfigurationRoute
  '/login': typeof LoginRoute
  '/manual-review': typeof ManualReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/inbox-configuration'
    | '/login'
    | '/manual-review'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/inbox-configuration' | '/login' | '/manual-review'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/inbox-configuration'
    | '/login'
    | '/manual-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InboxConfigurationRoute: typeof InboxConfigurationRoute
  LoginRoute: typeof LoginRoute
  ManualReviewRoute: typeof ManualReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manual-review': {
      id: '/manual-review'
      path: '/manual-review'
      fullPath: '/manual-review'
      preLoaderRoute: typeof ManualReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox-configuration': {
      id: '/inbox-configuration'
      path: '/inbox-configuration'
      fullPath: '/inbox-configuration'
      preLoaderRoute: typeof InboxConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InboxConfigurationRoute: InboxConfigurationRoute,
  LoginRoute: LoginRoute,
  ManualReviewRoute: ManualReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
